<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkplug_b.proto

namespace Sparkplug\Payload\Payload\Template\Parameter;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Payload.Template.Parameter.ParameterValueExtension</code>
 */
class ParameterValueExtension extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 1;</code>
     */
    private $extensions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Any[] $extensions
     * }
     */
    public function __construct($data = NULL) {
        \Sparkplug\Payload\Metadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 1;</code>
     * @return RepeatedField<\Google\Protobuf\Any>
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 1;</code>
     * @param \Google\Protobuf\Any[] $var
     * @return $this
     */
    public function setExtensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->extensions = $arr;

        return $this;
    }

}

