<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkplug_b.proto

namespace Sparkplug\Payload\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Payload.MetaData</code>
 */
class MetaData extends \Google\Protobuf\Internal\Message
{
    /**
     * Bytes specific metadata
     *
     * Generated from protobuf field <code>bool is_multi_part = 1;</code>
     */
    protected $is_multi_part = false;
    /**
     * General metadata
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     */
    protected $content_type = '';
    /**
     * File size, String size, Multi-part size, etc
     *
     * Generated from protobuf field <code>uint64 size = 3;</code>
     */
    protected $size = 0;
    /**
     * Sequence number for multi-part messages
     *
     * Generated from protobuf field <code>optional uint64 seq = 4;</code>
     */
    protected $seq = null;
    /**
     * File metadata
     *
     * Generated from protobuf field <code>string file_name = 5;</code>
     */
    protected $file_name = '';
    /**
     * File type (i.e. xml, json, txt, cpp, etc)
     *
     * Generated from protobuf field <code>string file_type = 6;</code>
     */
    protected $file_type = '';
    /**
     * md5 of data
     *
     * Generated from protobuf field <code>string md5 = 7;</code>
     */
    protected $md5 = '';
    /**
     * Catchalls and future expansion
     *
     * Generated from protobuf field <code>string description = 8;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 9;</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_multi_part
     *           Bytes specific metadata
     *     @type string $content_type
     *           General metadata
     *     @type int|string $size
     *           File size, String size, Multi-part size, etc
     *     @type int|string $seq
     *           Sequence number for multi-part messages
     *     @type string $file_name
     *           File metadata
     *     @type string $file_type
     *           File type (i.e. xml, json, txt, cpp, etc)
     *     @type string $md5
     *           md5 of data
     *     @type string $description
     *           Catchalls and future expansion
     *     @type \Google\Protobuf\Any[] $details
     * }
     */
    public function __construct($data = NULL) {
        \Sparkplug\Payload\Metadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * Bytes specific metadata
     *
     * Generated from protobuf field <code>bool is_multi_part = 1;</code>
     * @return bool
     */
    public function getIsMultiPart()
    {
        return $this->is_multi_part;
    }

    /**
     * Bytes specific metadata
     *
     * Generated from protobuf field <code>bool is_multi_part = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMultiPart($var)
    {
        GPBUtil::checkBool($var);
        $this->is_multi_part = $var;

        return $this;
    }

    /**
     * General metadata
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * General metadata
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->content_type = $var;

        return $this;
    }

    /**
     * File size, String size, Multi-part size, etc
     *
     * Generated from protobuf field <code>uint64 size = 3;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * File size, String size, Multi-part size, etc
     *
     * Generated from protobuf field <code>uint64 size = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Sequence number for multi-part messages
     *
     * Generated from protobuf field <code>optional uint64 seq = 4;</code>
     * @return int|string
     */
    public function getSeq()
    {
        return isset($this->seq) ? $this->seq : 0;
    }

    public function hasSeq()
    {
        return isset($this->seq);
    }

    public function clearSeq()
    {
        unset($this->seq);
    }

    /**
     * Sequence number for multi-part messages
     *
     * Generated from protobuf field <code>optional uint64 seq = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint64($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * File metadata
     *
     * Generated from protobuf field <code>string file_name = 5;</code>
     * @return string
     */
    public function getFileName()
    {
        return $this->file_name;
    }

    /**
     * File metadata
     *
     * Generated from protobuf field <code>string file_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_name = $var;

        return $this;
    }

    /**
     * File type (i.e. xml, json, txt, cpp, etc)
     *
     * Generated from protobuf field <code>string file_type = 6;</code>
     * @return string
     */
    public function getFileType()
    {
        return $this->file_type;
    }

    /**
     * File type (i.e. xml, json, txt, cpp, etc)
     *
     * Generated from protobuf field <code>string file_type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFileType($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_type = $var;

        return $this;
    }

    /**
     * md5 of data
     *
     * Generated from protobuf field <code>string md5 = 7;</code>
     * @return string
     */
    public function getMd5()
    {
        return $this->md5;
    }

    /**
     * md5 of data
     *
     * Generated from protobuf field <code>string md5 = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMd5($var)
    {
        GPBUtil::checkString($var, True);
        $this->md5 = $var;

        return $this;
    }

    /**
     * Catchalls and future expansion
     *
     * Generated from protobuf field <code>string description = 8;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Catchalls and future expansion
     *
     * Generated from protobuf field <code>string description = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 9;</code>
     * @return RepeatedField<\Google\Protobuf\Any>
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 9;</code>
     * @param \Google\Protobuf\Any[] $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->details = $arr;

        return $this;
    }

}

