<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkplug_b.proto

namespace Sparkplug\Payload\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Payload.PropertySet</code>
 */
class PropertySet extends \Google\Protobuf\Internal\Message
{
    /**
     * Names of the properties
     *
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>repeated .Payload.PropertyValue values = 2;</code>
     */
    private $values;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 3;</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $keys
     *           Names of the properties
     *     @type \Sparkplug\Payload\Payload\PropertyValue[] $values
     *     @type \Google\Protobuf\Any[] $details
     * }
     */
    public function __construct($data = NULL) {
        \Sparkplug\Payload\Metadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * Names of the properties
     *
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     * @return RepeatedField<string>
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Names of the properties
     *
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Payload.PropertyValue values = 2;</code>
     * @return RepeatedField<\Sparkplug\Payload\Payload\PropertyValue>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .Payload.PropertyValue values = 2;</code>
     * @param \Sparkplug\Payload\Payload\PropertyValue[] $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sparkplug\Payload\Payload\PropertyValue::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 3;</code>
     * @return RepeatedField<\Google\Protobuf\Any>
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 3;</code>
     * @param \Google\Protobuf\Any[] $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->details = $arr;

        return $this;
    }

}

