<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkplug_b.proto

namespace Sparkplug\Payload\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Payload.PropertySetList</code>
 */
class PropertySetList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Payload.PropertySet propertyset = 1;</code>
     */
    private $propertyset;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 2;</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sparkplug\Payload\Payload\PropertySet[] $propertyset
     *     @type \Google\Protobuf\Any[] $details
     * }
     */
    public function __construct($data = NULL) {
        \Sparkplug\Payload\Metadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Payload.PropertySet propertyset = 1;</code>
     * @return RepeatedField<\Sparkplug\Payload\Payload\PropertySet>
     */
    public function getPropertyset()
    {
        return $this->propertyset;
    }

    /**
     * Generated from protobuf field <code>repeated .Payload.PropertySet propertyset = 1;</code>
     * @param \Sparkplug\Payload\Payload\PropertySet[] $var
     * @return $this
     */
    public function setPropertyset($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sparkplug\Payload\Payload\PropertySet::class);
        $this->propertyset = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 2;</code>
     * @return RepeatedField<\Google\Protobuf\Any>
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 2;</code>
     * @param \Google\Protobuf\Any[] $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->details = $arr;

        return $this;
    }

}

