<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkplug_b.proto

namespace Sparkplug\Payload\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Payload.PropertyValue</code>
 */
class PropertyValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>bool is_null = 2;</code>
     */
    protected $is_null = false;
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type bool $is_null
     *     @type int $int_value
     *     @type int|string $long_value
     *     @type float $float_value
     *     @type float $double_value
     *     @type bool $boolean_value
     *     @type string $string_value
     *     @type \Sparkplug\Payload\Payload\PropertySet $propertyset_value
     *     @type \Sparkplug\Payload\Payload\PropertySetList $propertysets_value
     *           List of Property Values
     *     @type \Sparkplug\Payload\Payload\PropertyValue\PropertyValueExtension $extension_value
     * }
     */
    public function __construct($data = NULL) {
        \Sparkplug\Payload\Metadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>uint32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_null = 2;</code>
     * @return bool
     */
    public function getIsNull()
    {
        return $this->is_null;
    }

    /**
     * Generated from protobuf field <code>bool is_null = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->is_null = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 int_value = 3;</code>
     * @return int
     */
    public function getIntValue()
    {
        return $this->readOneof(3);
    }

    public function hasIntValue()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>uint32 int_value = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIntValue($var)
    {
        GPBUtil::checkUint32($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 long_value = 4;</code>
     * @return int|string
     */
    public function getLongValue()
    {
        return $this->readOneof(4);
    }

    public function hasLongValue()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>uint64 long_value = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLongValue($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>float float_value = 5;</code>
     * @return float
     */
    public function getFloatValue()
    {
        return $this->readOneof(5);
    }

    public function hasFloatValue()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>float float_value = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setFloatValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_value = 6;</code>
     * @return float
     */
    public function getDoubleValue()
    {
        return $this->readOneof(6);
    }

    public function hasDoubleValue()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>double double_value = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 7;</code>
     * @return bool
     */
    public function getBooleanValue()
    {
        return $this->readOneof(7);
    }

    public function hasBooleanValue()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setBooleanValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_value = 8;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(8);
    }

    public function hasStringValue()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>string string_value = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Payload.PropertySet propertyset_value = 9;</code>
     * @return \Sparkplug\Payload\Payload\PropertySet|null
     */
    public function getPropertysetValue()
    {
        return $this->readOneof(9);
    }

    public function hasPropertysetValue()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.Payload.PropertySet propertyset_value = 9;</code>
     * @param \Sparkplug\Payload\Payload\PropertySet $var
     * @return $this
     */
    public function setPropertysetValue($var)
    {
        GPBUtil::checkMessage($var, \Sparkplug\Payload\Payload\PropertySet::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * List of Property Values
     *
     * Generated from protobuf field <code>.Payload.PropertySetList propertysets_value = 10;</code>
     * @return \Sparkplug\Payload\Payload\PropertySetList|null
     */
    public function getPropertysetsValue()
    {
        return $this->readOneof(10);
    }

    public function hasPropertysetsValue()
    {
        return $this->hasOneof(10);
    }

    /**
     * List of Property Values
     *
     * Generated from protobuf field <code>.Payload.PropertySetList propertysets_value = 10;</code>
     * @param \Sparkplug\Payload\Payload\PropertySetList $var
     * @return $this
     */
    public function setPropertysetsValue($var)
    {
        GPBUtil::checkMessage($var, \Sparkplug\Payload\Payload\PropertySetList::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Payload.PropertyValue.PropertyValueExtension extension_value = 11;</code>
     * @return \Sparkplug\Payload\Payload\PropertyValue\PropertyValueExtension|null
     */
    public function getExtensionValue()
    {
        return $this->readOneof(11);
    }

    public function hasExtensionValue()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.Payload.PropertyValue.PropertyValueExtension extension_value = 11;</code>
     * @param \Sparkplug\Payload\Payload\PropertyValue\PropertyValueExtension $var
     * @return $this
     */
    public function setExtensionValue($var)
    {
        GPBUtil::checkMessage($var, \Sparkplug\Payload\Payload\PropertyValue\PropertyValueExtension::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

