<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkplug_b.proto

namespace Sparkplug\Payload\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Payload.Template</code>
 */
class Template extends \Google\Protobuf\Internal\Message
{
    /**
     * The version of the Template to prevent mismatches
     *
     * Generated from protobuf field <code>string version = 1;</code>
     */
    protected $version = '';
    /**
     * Each metric is the name of the metric and the datatype of the member but does not contain a value
     *
     * Generated from protobuf field <code>repeated .Payload.Metric metrics = 2;</code>
     */
    private $metrics;
    /**
     * Generated from protobuf field <code>repeated .Payload.Template.Parameter parameters = 3;</code>
     */
    private $parameters;
    /**
     * Reference to a template if this is extending a Template or an instance - must exist if an instance
     *
     * Generated from protobuf field <code>string template_ref = 4;</code>
     */
    protected $template_ref = '';
    /**
     * Generated from protobuf field <code>bool is_definition = 5;</code>
     */
    protected $is_definition = false;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 6;</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *           The version of the Template to prevent mismatches
     *     @type \Sparkplug\Payload\Payload\Metric[] $metrics
     *           Each metric is the name of the metric and the datatype of the member but does not contain a value
     *     @type \Sparkplug\Payload\Payload\Template\Parameter[] $parameters
     *     @type string $template_ref
     *           Reference to a template if this is extending a Template or an instance - must exist if an instance
     *     @type bool $is_definition
     *     @type \Google\Protobuf\Any[] $details
     * }
     */
    public function __construct($data = NULL) {
        \Sparkplug\Payload\Metadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * The version of the Template to prevent mismatches
     *
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * The version of the Template to prevent mismatches
     *
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Each metric is the name of the metric and the datatype of the member but does not contain a value
     *
     * Generated from protobuf field <code>repeated .Payload.Metric metrics = 2;</code>
     * @return RepeatedField<\Sparkplug\Payload\Payload\Metric>
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    /**
     * Each metric is the name of the metric and the datatype of the member but does not contain a value
     *
     * Generated from protobuf field <code>repeated .Payload.Metric metrics = 2;</code>
     * @param \Sparkplug\Payload\Payload\Metric[] $var
     * @return $this
     */
    public function setMetrics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sparkplug\Payload\Payload\Metric::class);
        $this->metrics = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Payload.Template.Parameter parameters = 3;</code>
     * @return RepeatedField<\Sparkplug\Payload\Payload\Template\Parameter>
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>repeated .Payload.Template.Parameter parameters = 3;</code>
     * @param \Sparkplug\Payload\Payload\Template\Parameter[] $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sparkplug\Payload\Payload\Template\Parameter::class);
        $this->parameters = $arr;

        return $this;
    }

    /**
     * Reference to a template if this is extending a Template or an instance - must exist if an instance
     *
     * Generated from protobuf field <code>string template_ref = 4;</code>
     * @return string
     */
    public function getTemplateRef()
    {
        return $this->template_ref;
    }

    /**
     * Reference to a template if this is extending a Template or an instance - must exist if an instance
     *
     * Generated from protobuf field <code>string template_ref = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->template_ref = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_definition = 5;</code>
     * @return bool
     */
    public function getIsDefinition()
    {
        return $this->is_definition;
    }

    /**
     * Generated from protobuf field <code>bool is_definition = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDefinition($var)
    {
        GPBUtil::checkBool($var);
        $this->is_definition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 6;</code>
     * @return RepeatedField<\Google\Protobuf\Any>
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 6;</code>
     * @param \Google\Protobuf\Any[] $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->details = $arr;

        return $this;
    }

}

