<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkplug_b.proto

namespace Sparkplug\Payload;

use UnexpectedValueException;

/**
 * Indexes of Data Types
 *
 * Protobuf type <code>DataType</code>
 */
class DataType
{
    /**
     * Unknown placeholder for future expansion.
     *
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Basic Types
     *
     * Generated from protobuf enum <code>Int8 = 1;</code>
     */
    const Int8 = 1;
    /**
     * Generated from protobuf enum <code>Int16 = 2;</code>
     */
    const Int16 = 2;
    /**
     * Generated from protobuf enum <code>Int32 = 3;</code>
     */
    const Int32 = 3;
    /**
     * Generated from protobuf enum <code>Int64 = 4;</code>
     */
    const Int64 = 4;
    /**
     * Generated from protobuf enum <code>UInt8 = 5;</code>
     */
    const UInt8 = 5;
    /**
     * Generated from protobuf enum <code>UInt16 = 6;</code>
     */
    const UInt16 = 6;
    /**
     * Generated from protobuf enum <code>UInt32 = 7;</code>
     */
    const UInt32 = 7;
    /**
     * Generated from protobuf enum <code>UInt64 = 8;</code>
     */
    const UInt64 = 8;
    /**
     * Generated from protobuf enum <code>Float = 9;</code>
     */
    const Float = 9;
    /**
     * Generated from protobuf enum <code>Double = 10;</code>
     */
    const Double = 10;
    /**
     * Generated from protobuf enum <code>Boolean = 11;</code>
     */
    const Boolean = 11;
    /**
     * Generated from protobuf enum <code>String = 12;</code>
     */
    const String = 12;
    /**
     * Generated from protobuf enum <code>DateTime = 13;</code>
     */
    const DateTime = 13;
    /**
     * Generated from protobuf enum <code>Text = 14;</code>
     */
    const Text = 14;
    /**
     * Additional Metric Types
     *
     * Generated from protobuf enum <code>UUID = 15;</code>
     */
    const UUID = 15;
    /**
     * Generated from protobuf enum <code>DataSet = 16;</code>
     */
    const DataSet = 16;
    /**
     * Generated from protobuf enum <code>Bytes = 17;</code>
     */
    const Bytes = 17;
    /**
     * Generated from protobuf enum <code>File = 18;</code>
     */
    const File = 18;
    /**
     * Generated from protobuf enum <code>Template = 19;</code>
     */
    const Template = 19;
    /**
     * Additional PropertyValue Types
     *
     * Generated from protobuf enum <code>PropertySet = 20;</code>
     */
    const PropertySet = 20;
    /**
     * Generated from protobuf enum <code>PropertySetList = 21;</code>
     */
    const PropertySetList = 21;
    /**
     * Array Types
     *
     * Generated from protobuf enum <code>Int8Array = 22;</code>
     */
    const Int8Array = 22;
    /**
     * Generated from protobuf enum <code>Int16Array = 23;</code>
     */
    const Int16Array = 23;
    /**
     * Generated from protobuf enum <code>Int32Array = 24;</code>
     */
    const Int32Array = 24;
    /**
     * Generated from protobuf enum <code>Int64Array = 25;</code>
     */
    const Int64Array = 25;
    /**
     * Generated from protobuf enum <code>UInt8Array = 26;</code>
     */
    const UInt8Array = 26;
    /**
     * Generated from protobuf enum <code>UInt16Array = 27;</code>
     */
    const UInt16Array = 27;
    /**
     * Generated from protobuf enum <code>UInt32Array = 28;</code>
     */
    const UInt32Array = 28;
    /**
     * Generated from protobuf enum <code>UInt64Array = 29;</code>
     */
    const UInt64Array = 29;
    /**
     * Generated from protobuf enum <code>FloatArray = 30;</code>
     */
    const FloatArray = 30;
    /**
     * Generated from protobuf enum <code>DoubleArray = 31;</code>
     */
    const DoubleArray = 31;
    /**
     * Generated from protobuf enum <code>BooleanArray = 32;</code>
     */
    const BooleanArray = 32;
    /**
     * Generated from protobuf enum <code>StringArray = 33;</code>
     */
    const StringArray = 33;
    /**
     * Generated from protobuf enum <code>DateTimeArray = 34;</code>
     */
    const DateTimeArray = 34;

    private static $valueToName = [
        self::Unknown => 'Unknown',
        self::Int8 => 'Int8',
        self::Int16 => 'Int16',
        self::Int32 => 'Int32',
        self::Int64 => 'Int64',
        self::UInt8 => 'UInt8',
        self::UInt16 => 'UInt16',
        self::UInt32 => 'UInt32',
        self::UInt64 => 'UInt64',
        self::Float => 'Float',
        self::Double => 'Double',
        self::Boolean => 'Boolean',
        self::String => 'String',
        self::DateTime => 'DateTime',
        self::Text => 'Text',
        self::UUID => 'UUID',
        self::DataSet => 'DataSet',
        self::Bytes => 'Bytes',
        self::File => 'File',
        self::Template => 'Template',
        self::PropertySet => 'PropertySet',
        self::PropertySetList => 'PropertySetList',
        self::Int8Array => 'Int8Array',
        self::Int16Array => 'Int16Array',
        self::Int32Array => 'Int32Array',
        self::Int64Array => 'Int64Array',
        self::UInt8Array => 'UInt8Array',
        self::UInt16Array => 'UInt16Array',
        self::UInt32Array => 'UInt32Array',
        self::UInt64Array => 'UInt64Array',
        self::FloatArray => 'FloatArray',
        self::DoubleArray => 'DoubleArray',
        self::BooleanArray => 'BooleanArray',
        self::StringArray => 'StringArray',
        self::DateTimeArray => 'DateTimeArray',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

