<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkplug_b.proto

namespace Sparkplug\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * Timestamp at message sending time
     *
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     */
    protected $timestamp = 0;
    /**
     * Repeated forever - no limit in Google Protobufs
     *
     * Generated from protobuf field <code>repeated .Payload.Metric metrics = 2;</code>
     */
    private $metrics;
    /**
     * Sequence number
     *
     * Generated from protobuf field <code>optional uint64 seq = 3;</code>
     */
    protected $seq = null;
    /**
     * UUID to track message type in terms of schema definitions
     *
     * Generated from protobuf field <code>string uuid = 4;</code>
     */
    protected $uuid = '';
    /**
     * To optionally bypass the whole definition above
     *
     * Generated from protobuf field <code>bytes body = 5;</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 6;</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *           Timestamp at message sending time
     *     @type \Sparkplug\Payload\Payload\Metric[] $metrics
     *           Repeated forever - no limit in Google Protobufs
     *     @type int|string $seq
     *           Sequence number
     *     @type string $uuid
     *           UUID to track message type in terms of schema definitions
     *     @type string $body
     *           To optionally bypass the whole definition above
     *     @type \Google\Protobuf\Any[] $details
     * }
     */
    public function __construct($data = NULL) {
        \Sparkplug\Payload\Metadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * Timestamp at message sending time
     *
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Timestamp at message sending time
     *
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Repeated forever - no limit in Google Protobufs
     *
     * Generated from protobuf field <code>repeated .Payload.Metric metrics = 2;</code>
     * @return RepeatedField<\Sparkplug\Payload\Payload\Metric>
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    /**
     * Repeated forever - no limit in Google Protobufs
     *
     * Generated from protobuf field <code>repeated .Payload.Metric metrics = 2;</code>
     * @param \Sparkplug\Payload\Payload\Metric[] $var
     * @return $this
     */
    public function setMetrics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sparkplug\Payload\Payload\Metric::class);
        $this->metrics = $arr;

        return $this;
    }

    /**
     * Sequence number
     *
     * Generated from protobuf field <code>optional uint64 seq = 3;</code>
     * @return int|string
     */
    public function getSeq()
    {
        return isset($this->seq) ? $this->seq : 0;
    }

    public function hasSeq()
    {
        return isset($this->seq);
    }

    public function clearSeq()
    {
        unset($this->seq);
    }

    /**
     * Sequence number
     *
     * Generated from protobuf field <code>optional uint64 seq = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint64($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * UUID to track message type in terms of schema definitions
     *
     * Generated from protobuf field <code>string uuid = 4;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * UUID to track message type in terms of schema definitions
     *
     * Generated from protobuf field <code>string uuid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * To optionally bypass the whole definition above
     *
     * Generated from protobuf field <code>bytes body = 5;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * To optionally bypass the whole definition above
     *
     * Generated from protobuf field <code>bytes body = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 6;</code>
     * @return RepeatedField<\Google\Protobuf\Any>
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.Any details = 6;</code>
     * @param \Google\Protobuf\Any[] $var
     * @return $this
     */
    public function setDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->details = $arr;

        return $this;
    }

}

